Branch entrega3
elagarrigue/AyDS23-NewYork2 pull request #3
Opened 2023-05-10 13:40 UTC by rodrikraus

Pull request asociado a la entrega 3. Se modifica la estructura del paquete moredetails para que corresponda a una arquitectura Clean MVP, siempre respetando los principios SOLID y clean code.. Se encuentra en la carpeta docs el diagrama de clases asociado (sin atributos ni métodos).

2023-05-11 22:37 UTC, FabioCampetti commented on app/src/main/java/ayds/newyork/songinfo/moredetails/data/repository/external/nytimes/service/NYTimesServiceImpl.kt
> +internal class NYTimesServiceImpl(
Definir la interface en este archivo

2023-05-11 22:38 UTC, FabioCampetti commented on app/src/main/java/ayds/newyork/songinfo/moredetails/data/repository/local/sqldb/ArtistLocalStorageImpl.kt
> +internal class ArtistLocalStorageImpl(context: Context, private val cursorToArtistDataMapper: CursorToArtistDataMapper) : SQLiteOpenHelper(context, DATABASE_NAME, null, DATABASE_VERSION),
Definir la interface en este archivo

2023-05-11 22:46 UTC, FabioCampetti commented on app/src/main/java/ayds/newyork/songinfo/moredetails/data/repository/external/nytimes/service/NYTimesServiceImpl.kt
> +    override fun getURL(artistName: String?): String {
Mover esta funcion al resolver

2023-05-11 22:46 UTC, FabioCampetti commented on app/src/main/java/ayds/newyork/songinfo/moredetails/data/repository/external/nytimes/service/NYTimesServiceImpl.kt
> +    private fun generateResponse(artistName: String?): JsonObject {
Mover esta funcion al resolver

2023-05-11 22:46 UTC, FabioCampetti commented on app/src/main/java/ayds/newyork/songinfo/moredetails/data/repository/external/nytimes/service/NYTimesServiceImpl.kt
> +    private fun generateFormattedResponse(nameArtist: String?): String? {
Mover esta funcion al resolver

2023-05-11 22:48 UTC, FabioCampetti commented on app/src/main/java/ayds/newyork/songinfo/moredetails/data/repository/external/nytimes/service/NYTimesServiceImpl.kt
> +private const val PROP_RESPONSE = "response"
Mover constantes al resolver

2023-05-11 22:51 UTC, FabioCampetti commented on app/src/main/java/ayds/newyork/songinfo/moredetails/domain/repository/ArtistRepository.kt
> +}
Añadir linea en blanco

2023-05-11 23:00 UTC, FabioCampetti commented on app/src/main/java/ayds/newyork/songinfo/moredetails/MoreDetailsInjector.kt
> +    private fun initNYTimesService(): NYTimesService {
Separar en dos funciones. Una para Inizilizar el servicio y otra para Buildear el retrofit.

2023-05-15 12:20 UTC, FabioCampetti commented on app/src/main/java/ayds/newyork/songinfo/moredetails/data/repository/external/nytimes/service/NYTimesToArtistResolver.kt
> +    override fun artistInfoAbstractToString(abstract: JsonElement, nameArtist: String?): String {
Definir funcion como privada

2023-05-15 12:20 UTC, FabioCampetti commented on app/src/main/java/ayds/newyork/songinfo/moredetails/data/repository/external/nytimes/service/NYTimesToArtistResolver.kt
> +    override fun getAsJsonObject(response: JsonObject): JsonElement? {
Definir funcion como privada

2023-05-15 12:21 UTC, FabioCampetti commented on app/src/main/java/ayds/newyork/songinfo/moredetails/data/repository/external/nytimes/service/NYTimesToArtistResolver.kt
> +    override fun getJson(callResponse: Response<String>): JsonObject {
Definir funcion como privada

2023-05-15 12:30 UTC, FabioCampetti commented on app/src/main/java/ayds/newyork/songinfo/moredetails/presentation/presenter/MoreDetailsPresenter.kt
> +    override val uiStateObservable:Observable<MoreDetailsUIState> = onUIStateSubject
` uiStateObservable = onUIStateSubject`

2023-05-15 12:32 UTC, FabioCampetti commented on app/src/main/java/ayds/newyork/songinfo/moredetails/presentation/presenter/MoreDetailsPresenter.kt
> +        onUIStateSubject.notify(uiState!!)
`uiStateObservable.notify(uiState)`

2023-05-15 12:44 UTC, FabioCampetti commented
Añadir el Servicio Externo y la BD al diagrama.
La dependencia del modulo presentation con el injector es hacia ambos lados.
La dependencia de MoreDetailsPresenterImpl debe ser hacia una clase en especifica, no hacia todo el modulo.

2023-05-16 20:50 UTC, kevschweitzer requested changes

2023-05-16 20:50 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/presentation/presenter/MoreDetailsPresenter.kt
> +        onUIStateSubject.notify(uiState!!)
Por que hay 2 notify?

2023-05-16 20:50 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/presentation/presenter/RepositoryToViewFormatter.kt
> +                    textToHTML("$NOT_IN_LOCAL_REPOSITORY${artist.info}", artist.name)
No es necesario el NOT_IN_LOCAL_REPOSITORY. Si es vacio no agrega nada.

2023-05-16 20:50 UTC, kevschweitzer commented on app/src/main/java/ayds/newyork/songinfo/moredetails/presentation/presenter/MoreDetailsPresenter.kt
> +        val artistData = repository.getArtistData(artistName!!)
No usar nunca !! sin haber chequeado que no sea nulo. En este caso veo que ni siquiera es necesario

2023-05-17 12:23 UTC, merged